# coding:utf-8
# 导入模块
import Cython.Build

if __name__ == '__main__':
    # 传入要编译成pyd的py文件
    ext1 = Cython.Build.cythonize("LostAndFoundService.py")
    ext2 = Cython.Build.cythonize("FeedbackService.py")
    ext3 = Cython.Build.cythonize("CompanyService.py")
    ext4 = Cython.Build.cythonize("RouteService.py")
    ext5 = Cython.Build.cythonize("CertificationService.py")
    ext6 = Cython.Build.cythonize("PassengerIdentityService.py")
    ext7 = Cython.Build.cythonize("CarService.py")
    ext8 = Cython.Build.cythonize("UserProfileService.py")
    ext9 = Cython.Build.cythonize("SettlementService.py")
    ext10 = Cython.Build.cythonize("MiniService.py")
    ext11 = Cython.Build.cythonize("AdvertService.py")
    ext12 = Cython.Build.cythonize("NoticeService.py")
    ext13 = Cython.Build.cythonize("OrderService.py")
    ext14 = Cython.Build.cythonize("CouponService.py")
    ext15 = Cython.Build.cythonize("AdminUserService.py")
    ext16 = Cython.Build.cythonize("IdentityService.py")
    ext17 = Cython.Build.cythonize("CouponTypeService.py")
    ext18 = Cython.Build.cythonize("DeviceService.py")
    ext19 = Cython.Build.cythonize("IndexHomeService.py")
    ext20 = Cython.Build.cythonize("MenuService.py")
    ext21 = Cython.Build.cythonize("RoleService.py")
    ext22 = Cython.Build.cythonize("StationService.py")
    ext23 = Cython.Build.cythonize("ClientDeviceService.py")
    ext24 = Cython.Build.cythonize("ClientAppService.py")
    ext25 = Cython.Build.cythonize("DistrictCodeService.py")
    ext26 = Cython.Build.cythonize("BillService.py")
    ext27 = Cython.Build.cythonize("RechargeService.py")
    ext28 = Cython.Build.cythonize("CallbackService.py")
    # 下面还要导入另一个模块
    import distutils.core

    # 调用setup方法
    distutils.core.setup(ext_modules=ext1)
    distutils.core.setup(ext_modules=ext2)
    distutils.core.setup(ext_modules=ext3)
    distutils.core.setup(ext_modules=ext4)
    distutils.core.setup(ext_modules=ext5)
    distutils.core.setup(ext_modules=ext6)
    distutils.core.setup(ext_modules=ext7)
    distutils.core.setup(ext_modules=ext8)
    distutils.core.setup(ext_modules=ext9)
    distutils.core.setup(ext_modules=ext10)
    distutils.core.setup(ext_modules=ext11)
    distutils.core.setup(ext_modules=ext12)
    distutils.core.setup(ext_modules=ext13)
    distutils.core.setup(ext_modules=ext14)
    distutils.core.setup(ext_modules=ext15)
    distutils.core.setup(ext_modules=ext16)
    distutils.core.setup(ext_modules=ext17)
    distutils.core.setup(ext_modules=ext18)
    distutils.core.setup(ext_modules=ext19)
    distutils.core.setup(ext_modules=ext20)
    distutils.core.setup(ext_modules=ext21)
    distutils.core.setup(ext_modules=ext22)
    distutils.core.setup(ext_modules=ext23)
    distutils.core.setup(ext_modules=ext24)
    distutils.core.setup(ext_modules=ext25)
    distutils.core.setup(ext_modules=ext26)
    distutils.core.setup(ext_modules=ext27)
    distutils.core.setup(ext_modules=ext28)
