# coding:utf-8
# 导入模块
import Cython.Build

if __name__ == '__main__':
    # 传入要编译成pyd的py文件
    ext1 = Cython.Build.cythonize("CallbackController.py")
    ext2 = Cython.Build.cythonize("IdentityController.py")
    ext3 = Cython.Build.cythonize("CertificationController.py")
    ext4 = Cython.Build.cythonize("AdminUserController.py")
    ext5 = Cython.Build.cythonize("StationController.py")
    ext6 = Cython.Build.cythonize("NoticeController.py")
    ext7 = Cython.Build.cythonize("OrderController.py")
    ext8 = Cython.Build.cythonize("CouponTypeController.py")
    ext9 = Cython.Build.cythonize("DeviceController.py")
    ext10 = Cython.Build.cythonize("RechargeController.py")
    ext11 = Cython.Build.cythonize("SettlementController.py")
    ext12 = Cython.Build.cythonize("CouponController.py")
    ext13 = Cython.Build.cythonize("ClientAppController.py")
    ext14 = Cython.Build.cythonize("ClientDeviceController.py")
    ext15 = Cython.Build.cythonize("FeedbackController.py")
    ext16 = Cython.Build.cythonize("IndexHomeController.py")
    ext17 = Cython.Build.cythonize("LostAndFoundController.py")
    ext18 = Cython.Build.cythonize("MiniController.py")
    ext19 = Cython.Build.cythonize("AdvertController.py")
    ext20 = Cython.Build.cythonize("CarController.py")
    ext21 = Cython.Build.cythonize("DistrictCodeController.py")
    ext22 = Cython.Build.cythonize("PassengerIdentityController.py")
    ext23 = Cython.Build.cythonize("BillController.py")
    ext24 = Cython.Build.cythonize("BusRouteController.py")
    ext25 = Cython.Build.cythonize("RoleController.py")
    ext26 = Cython.Build.cythonize("CompanyController.py")
    ext27 = Cython.Build.cythonize("UserProfileController.py")
    # 下面还要导入另一个模块
    import distutils.core

    # 调用setup方法
    distutils.core.setup(ext_modules=ext1)
    distutils.core.setup(ext_modules=ext2)
    distutils.core.setup(ext_modules=ext3)
    distutils.core.setup(ext_modules=ext4)
    distutils.core.setup(ext_modules=ext5)
    distutils.core.setup(ext_modules=ext6)
    distutils.core.setup(ext_modules=ext7)
    distutils.core.setup(ext_modules=ext8)
    distutils.core.setup(ext_modules=ext9)
    distutils.core.setup(ext_modules=ext10)
    distutils.core.setup(ext_modules=ext11)
    distutils.core.setup(ext_modules=ext12)
    distutils.core.setup(ext_modules=ext13)
    distutils.core.setup(ext_modules=ext14)
    distutils.core.setup(ext_modules=ext15)
    distutils.core.setup(ext_modules=ext16)
    distutils.core.setup(ext_modules=ext17)
    distutils.core.setup(ext_modules=ext18)
    distutils.core.setup(ext_modules=ext19)
    distutils.core.setup(ext_modules=ext20)
    distutils.core.setup(ext_modules=ext21)
    distutils.core.setup(ext_modules=ext22)
    distutils.core.setup(ext_modules=ext23)
    distutils.core.setup(ext_modules=ext24)
    distutils.core.setup(ext_modules=ext25)
    distutils.core.setup(ext_modules=ext26)
    distutils.core.setup(ext_modules=ext27)